GCCFLAGS = -Wall -mlong-calls  -nostdlib -fno-builtin  -mcpu=arm7tdmi -Os
#-Os -mlong-calls 

#GCCFLAGS +=   -fomit-frame-pointer -fno-strict-aliasing


ASFLAGS = -mfpu=softfpa

# target AV3XX or GMINI4XX

TARGET_DEVICE = AV3XX

GCCFLAGS += -D$(TARGET_DEVICE)

TOOL=arm-linux-uclibc
GCC=$(TOOL)-gcc
AS=$(TOOL)-as
LD=$(TOOL)-ld
OBJCOPY= $(TOOL)-objcopy
RM=rm
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib
MV=mv
