#type AV or X11
BUILD=AV
#values: y,n
HAVE_JPEG=y

ROOTPATH = /home/thomas/Av320/linav/gui2

ifeq ($(HAVE_JPEG),y)
GCCFLAGS +=-DHAVE_JPEG
endif

ifeq ($(BUILD),AV)
GCCFLAGS += -DAV_SCREEN -Wall
TOOL=arm-elf
GCC=$(TOOL)-gcc
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib
LDFLAGS=-elf2flt
else
GCC=gcc
AR=ar
RANLIB=ranlib
endif
