#type AV or X11
BUILD=AV
#values: y,n
HAVE_JPEG=y

ifeq ($(BUILD),AV)
GCCFLAGS += -D'GTYPE=AV_SCREEN'
TOOL=arm-elf
GCC=$(TOOL)-gcc
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib
LDFLAGS=-elf2flt
else
GCCFLAGS += -D'GTYPE=X11_SCREEN'
GCC=gcc
AR=ar
RANLIB=ranlib
endif