include ../../../Makefile.conf

ASFLAGS  += -I../../../include  -I. -I../ -I../apu -I../n6502
GCCFLAGS += -I../../../include -I. -I../ -I../apu -I../n6502 -O3

BUILD_DIR = ../build
all: do_build

include ../../../default.rule