
GCCFLAGS = -Wall -mlong-calls -nostdlib -fno-builtin 
#-fomit-frame-pointer
ASFLAGS = -mfpu=softfpa


TOOL=arm-linux
GCC=$(TOOL)-gcc
AS=$(TOOL)-as
LD=$(TOOL)-ld
OBJCOPY= $(TOOL)-objcopy
RM=rm
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib


