@ avOS - http://avos.sourceforge.net
@ Copyright (c) 2003 by Jimmy Moore
@
@ All files in this archive are subject to the GNU General Public License.
@ See the file COPYING in the source tree root for full license agreement.
@ This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
@ KIND, either express of implied.
@
@ AV300 Specifics
@
@ Date:     20/01/2004
@ Author:   By DoggerMoore
@

hardwareJBMM                =   1

ramStart                    =   0x08000000

lcdRegBacklight             =   0x02400200
lcdWidth                    =   336
lcdHeight                   =   240

ataRegData                  =   0x04000800
ataRegError                 =   0x04000900
ataRegNSector               =   0x04000a00
ataRegSector                =   0x04000b00
ataRegLCyl                  =   0x04000c00
ataRegHCyl                  =   0x04000d00
ataRegSelect                =   0x04000e00
ataRegStatus                =   0x04000f00
ataRegCommand               =   0x04000f00

