GCCFLAGS = -Wall -mlong-calls  -nostdlib -fno-builtin  -mcpu=arm7tdmi -Os
#-Os -mlong-calls 

#GCCFLAGS +=   -fomit-frame-pointer -fno-strict-aliasing


ASFLAGS = -mfpu=softfpa

# target AV3XX or AV1XX or JBMM

TARGET_DEVICE = AV1XX

HAVE_IMG = 0

GCCFLAGS += -D$(TARGET_DEVICE)

ifeq ($(HAVE_IMG),1)
GCCFLAGS += -DHAVE_IMG
endif

TOOL=arm-linux-uclibc
GCC=$(TOOL)-gcc
AS=$(TOOL)-as
LD=$(TOOL)-ld
OBJCOPY= $(TOOL)-objcopy
RM=rm
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib
MV=mv
