//********New Stuff here:*********
/*
This demo is meant to help explain OSD, fonts, and scrolling implementation.
If you read through all this stuff and have any questions, post to the avos-dev yahoo group
or you can email me if you have specific situations that you have questions about.
The commented code is meant to be read through, much of it depends upon ideas discussed in
other portions of the code in order to understand it.  Usually when I use a new function I
explain it fully, then when it's used again later I don't explain it again, unless it's used
in a new way.

I use all four main OSD layers, and implement scrolling in various ways to show a variety of
possibilities.  Of interest is probably how I implement 'smooth' horizontal scrolling, which
due to the way the OSD works requires some tricks for either video or bitmap layer whenever
you're needing to scroll a large window -- larger than the screen size that is.
Smooth Scrolling is easy though for any layer that is smaller than screen size.

This program doesn't deal too much with colors, but some basic explanations are given.
Using custom color pallettes will hopefully be demonstated in a seperate program, as well as
the use of the other OSD features not covered here:  Cursors, Border, Zoom, etc.

One note to keep in mind:  This demo usually only shows 2 layers at a time, but you should
know the basic order that all layers are displayed in, which can *not* be changed, so plan
your programs carefully from the start.  Starting at bottom, things are shown in this order:
BORDER -> VIDEO1 -> VIDEO2 -> BITMAP1 -> BITMAP2 -> CURSOR1 -> CURSOR2

Additionally, it seems right now that I can't get BITMAP2 layer to either blend or 
be transapent to show Bitmap1 under it...  it is blending/transparent to Video layers
succesfully, but does not allow Bitmap1 to show through also as would have been expected...
*/
//*********End New Stuff**********

#include <graphics.h>
#include <osdDSC25.h>
#include <buttons.h>
#include <fonts.h>
#include <ata.h>

void delay(unsigned int time);
void doScroll(int xdir, int ydir);

int scroll = 0;
int slow = 1;
int wait = 0x01200;
int xv = 0, yv = 0, xb = 60, yb = 100, xb2 = 6, yb2 = 0;

//make two-color pallettes for text on video (pal32) and bitmap (pal16) planes.
//First number is background color, second is text color.
static int pal32[2] = {0x00800080, 0xff80ff80}; //Y2CrY1Cb order, 32-bit color: {black,white}
static int pal16[2] = {0x0101, 0xffff}; //indexes to the 256-color pallette: {red,white}

//********New Stuff here:*********
//NOTE:  The Y2CrY1Cb color and the 16-bit-wide colors specified for the 256-color pallette
//       are explained here:  Really only the lowest 8 bits is used for the 256-color display
//       on bitmap layers, and only the lowest 24 bits is used for video layers...
//       But the extra highest 8 bits in either case exist because they are used when the
//       Hardware built-in "zoom" feature is used.  (OSD_BITMAP_ZX1, OSD_VIDEO_ZY2, etc)
//       This feature is not explained here, will be done in a future Demo program.
//       Suffice it to say that unless you zoom, doesn't matter what you set the highest
//       8 bits in the colors to.  If you zoom, the highest 8 bits are used to show the extra
//       pixels generated by the zoom.  By defining the upper 8 bits as a different color
//       you could therefore make graphics that show twice the detail when zoomed!
//       For bitmap planes, the upper 8 bits specifies a whole unique color for the zoomed
//       extra pixel detail.  For the video plane, the extra 8 bits is just the Y component,
//       So you can specify luminosity seperately, essentially, to give some extra detail...

//NOTE2: Video color is obvious, with standard YCbCr style colors.  Bitmap colors in this demo
//       are indexes to the built-in 256-color pallette.  To see the colors available and
//       associated values, use the palTest.bin available on avos site binaries section, or
//       available as C code in the CVS avos/src/examples directory.
//       It is possible to make your own 256-color pallette for use on the bitmap planes,
//       and it's not terribly difficult at all -- will demonstrate that in a future program.
//*********End New Stuff**********

//make structures for each video component/plane we'll be using (all four of them)
struct graphicsBuffer screenVideo;
struct graphicsBuffer screenVideo2;
struct graphicsBuffer screenBitmap2;
struct graphicsBuffer screenBitmap;

//make and init structures for each font we'll be using
//spriteFont5x8 will be filled manually in main(), the other three use short method
struct graphicsBuffer spriteFont5x8;
struct graphicsBuffer spriteFont7x13 =  {0,1,7,13,1,0,-1,0,0,0,0,(int**)&pal16,(int**)&pal32};
struct graphicsBuffer spriteFontCursive={0,2,9,15,1,0, 0,0,0,0,0,(int**)&pal16,(int**)&pal32};


int main() {

// Might as well power down HD and save battery :)

    ataPowerDownHDDA();

//-----------------INIT spriteFont5x8 STRUCTURE  ----------------------------
    //long way of initializing font structure spriteFont5x8:
    spriteFont5x8.offset = 0;               //no need to use offset for font sprites
    spriteFont5x8.bytesPerLine = 1;	        //# of bytes horizontally in font source per char.
    spriteFont5x8.width = 5;                //actual width of one character in pixels
    spriteFont5x8.height = 8;               //actual height in pixels
    spriteFont5x8.bitsPerPixel = 1;         //each pixel in font source uses 1 bit (2-color)
    spriteFont5x8.bitsPerPixelShift = 0;    //use 0 since this is only 2-color sprite
    spriteFont5x8.transparent = 0;          //color 0 index in font source shall be transparent
	                                        //-1=no transparancy, 1 would print inverse text?
    spriteFont5x8.pallette1 = 0;            //not necessary for font sprites
    spriteFont5x8.pallette2 = 0;            //ditto
    spriteFont5x8.pallette4 = 0;            //ditto
    spriteFont5x8.pallette8 = 0;            //ditto
    spriteFont5x8.pallette16 = (int**)&pal16;//point to our pal16 for printing on bitmap
    spriteFont5x8.pallette32 = (int**)&pal32;//point to our pal32 for printing on video

    //the short way of initializing font structures shown earlier, before main(), simply
    //  corresponds to this long way, each member is in order as shown here.
    //Note that the spriteFontCursive has '2' as bytesPerLine, cause it's 9pix wide that means
    //  the source uses 2 bytes for each line of each character.
    //Also note spriteFont7x13 has transparent member set to -1 (I don't want transparancy)


//-----------------INIT screenVideo AND screenBitmap STRUCTURES -------------

    //screenVideo will be size of LCD only
    screenVideo.offset = 0x03c00000;    //use typical address for video1 memory
    screenVideo.bytesPerLine = 320*4;   //320pixels wide * 4bytes (32-bits) per pixel
    screenVideo.width = 320;            //width 320pix
    screenVideo.height = 240;           //height 240pix
    screenVideo.bitsPerPixelShift = 5;  //use '5' for 32-bit graphics here
    screenVideo.bitsPerPixel = 32;      //must be 32 for video planes

    //screenVideo2 will be 640x480 for scrolling example
    screenVideo2.offset = 0x03e00000;   //use typical address for video2 memory
    screenVideo2.bytesPerLine = 640*4;  //640pix wide * 4bytes per pixel
    screenVideo2.width = 640;           //width 640pix!
    screenVideo2.height = 480;          //height 480pix!
    screenVideo2.bitsPerPixelShift = 5; //use '5' for 32-bit graphics
    screenVideo2.bitsPerPixel = 32;     //must use 32 for video planes
    
    //screenBitmap2 will be only 200x100 used for some text info, don't need whole screen
    //    It will also be scrollable though!
    screenBitmap2.offset = 0x03800000;   //address for bitmap2 memory, use whatever you want
                                         //   like other layers, just have enough space
    screenBitmap2.bytesPerLine = 208*2;  //208pix wide * 2bytes (16-bits) per pixel
      //Why 208 pix?  because the 200*2 wouldn't be a multiple of 32, the min boundary
      //   for scrolling purposes and offset changes.
      //   So, we use the next larger size divisible by 32 for better memory organization.
    screenBitmap2.width = 200;           //width 200pix
    screenBitmap2.height = 100;          //height 100pix
    screenBitmap2.bitsPerPixelShift = 4; //use '4' for 16-bit graphics
    screenBitmap2.bitsPerPixel = 16;     //must use 16 for bitmap planes

//********New Stuff here:*********
    //screenBitmap will be 784x360 for another large scrolling example, but only
    //    778x360 will be viewable after our tricks for large bitmap layer scrolling.
    screenBitmap.offset = 0x03a00000;   //address for bitmap memory, this is up to you
                                         //    like all the locations.  Just make sure each
                                         //    each layer has its own big enough space!
    screenBitmap.bytesPerLine = 784*2;  //784pix wide * 2bytes per pixel
    screenBitmap.width = 784;           //width 784pix! (note it's divisible by 32, must be)
    screenBitmap.height = 360;          //height 360pix!
    screenBitmap.bitsPerPixelShift = 4; //use '4' for 16-bit graphics
    screenBitmap.bitsPerPixel = 16;     //must use 16 for bitmap planes
//*********End New Stuff**********



//-----------------INIT OSD SYSTEM ------------------------------------------

    //call osdInit and disable everything just to be safe
    osdInitA();
    osdSetComponentConfigA(OSD_VIDEO1, 0);
    osdSetComponentConfigA(OSD_VIDEO2, 0);
    osdSetComponentConfigA(OSD_BITMAP1, 0);
    osdSetComponentConfigA(OSD_BITMAP2, 0);
    osdSetComponentConfigA(OSD_CURSOR1, 0);
    osdSetComponentConfigA(OSD_CURSOR2, 0);
    //set up VIDEO1 as needed; will correspond to our screenVideo structure
    osdSetComponentSizeA(OSD_VIDEO1, 640, 240);
            //640=twice desired window width, 240=desired window height
            //you always use twice desired width, even for bitmap components
    osdSetComponentPositionA(OSD_VIDEO1, 0x14, 0x12);
            //the typical position that sets this component at 0,0 of LCD
            //these numbers seem to get all components starting correctly at upper left of
            //the LCD, so use these as a basis.  Adding 2 to the x coordinate (0x14 now)
            //would shift display 1 pixel to right, adding 1 to y coordinate would shift
            //display 1 pixel down.  This applies to both video or bitmap components.
            //This setting can also be used later to scroll a window that's smaller than LCD.
    osdSetComponentOffsetA(OSD_VIDEO1, 0x03c00000);
            //point to our screenVideo memory, this is a setting that can later be used in
            //scrolling a window that's larger than the LCD.
    osdSetComponentSourceWidthA(OSD_VIDEO1, 0x28);
            //set to screenVideo.bytesPerLine divided by 32 (320*4/32 = 40 = 0x28)
            //note this is Source memory area width, not lcd or window width.  This is why
            //earlier we had to keep the BytesPerLine setting at multiples of 32...
    osdSetComponentConfigA(OSD_VIDEO1, 0);
            //keep the video1 component hidden for now, won't show on screen yet.

    //set up VIDEO2 as needed; will correspond to our screenVideo2 structure
    osdSetComponentSizeA(OSD_VIDEO2, 640, 240);
            //640=twice desired window width, 240=desired window height
    osdSetComponentPositionA(OSD_VIDEO2, 0x14, 0x12);
            //the typical position that sets this component at 0,0 of LCD
    osdSetComponentOffsetA(OSD_VIDEO2, 0x03e00000);
            //point to our screenVideo2 memory -- we'll alter this later for scrolling
            //  So for now it's showing the default top left of 640x480 video memory
            //Since this window is bigger than display, you could initialize it here to a 
            //  different default location...say you want LCD to show the middle lower
            //  area initially:  desired top left x,y would be something like 160,240 so
            //  you'd use 0x03e00000 + (y*4*640) + (x*4) or: 0x03e00000+(240*4*640)+(160*4).
            //  The '4' is number bytes per pixel, so you'd use '2' for bitmap planes.
            //  The '640' is number of pixels per line in the source memory
    osdSetComponentSourceWidthA(OSD_VIDEO2, 0x50);
            //set to screenVideo2.bytesPerLine divided by 32 (640*4/32 = 80 = 0x50)
    osdSetComponentConfigA(OSD_VIDEO2, 0);
            //keep it disabled for now, we'll switch between the two video planes later.

    //set up BITMAP2 as needed; will correspond to our screenBitmap2 structure
    osdSetComponentSizeA(OSD_BITMAP2, 400, 100);
            //400=twice desired window width, 100=desired window height
    osdSetComponentPositionA(OSD_BITMAP2, 0x14, 0x12);
            //the typical position that sets this component at 0,0 of LCD
            //this will start this window at 0,0 location (upper left).  Since this window
            //  is smaller than screen, we'd use this setting if we want to start it at a
            //  different spot on the screen.  Here it's always x*2 + 0x14, y+0x12.
            //  So if you want upper left of window at 50,70 you'd use (50*2 + 0x14, 70+0x12)
            //  THis formula does not change for video planes, use the same.
    osdSetComponentOffsetA(OSD_BITMAP2, 0x03800000);
            //point to our screenBitmap2 memory
    osdSetComponentSourceWidthA(OSD_BITMAP2, 0x0D);
            //set to screenBitmap2.bytesPerLine divided by 32 (208*2/32 = 13 = 0x0D)
    osdSetComponentConfigA(OSD_BITMAP2, 0);
            //keep it disabled until later

//********New Stuff here:*********
    //set up BITMAP1 as needed; will correspond to our screenBitmap structure

    //I'm using two tricks below here, that make smooth horizontal scrolling of large
    //  bitmaps possible.  And also setting Offset initially in the way that is required.
    //  I won't explain this process here, see the DoScroll routine.
    //If you only need basic scrolling (with coarse horizontal), you can of course set
    //  the initialization here to the usual values as shown in other layers above...
    osdSetComponentSizeA(OSD_BITMAP1, 684, 240);
            //trick #1 to help with smooth large bitmap scrolling...
    osdSetComponentPositionA(OSD_BITMAP1, 0x20 - 12, 0x12);
            //trick #2, a special position that will allow us to do necessary scrolling
            //  (also subtracted for the initial 0,0 top-left position of our window)
    osdSetComponentOffsetA(OSD_BITMAP1, 0x03a00000);
            //point to our screenBitmap memory
    osdSetComponentSourceWidthA(OSD_BITMAP1, 0x31);
            //set to screenBitmap.bytesPerLine divided by 32 (784*2/32 = 49 = 0x31)
    osdSetComponentConfigA(OSD_BITMAP1, 0);
            //keep it disabled for now
//*********End New Stuff**********


//------------------------ DRAW SOME STUFF ------------------------------------------

    int x,y,c;

    //draw a green border 4 pix wide around the 200x100 screenBitmap2 layer (BITMAP2)
    graphicsBoxfA(&screenBitmap2, 0, 0, 4, 100, 0xfafa); //green is 0xfa on built-in pallette
        //starts at 0,0 and draw 4 wide 100 high in green bitmap pallette color (left edge)
    graphicsBoxfA(&screenBitmap2, 196, 0, 4, 100, 0xfafa); //(right edge)
    graphicsBoxfA(&screenBitmap2, 0, 0, 200, 4, 0xfafa);  // (top edge)
    graphicsBoxfA(&screenBitmap2, 0, 96, 200, 4, 0xfafa);  //(bottom edge)
    //fill center area with dark gray background
    graphicsBoxfA(&screenBitmap2, 4,4,192,92,0x1212); //gray is 0x12 on built-in pallette
    //reposition box so that it's more in center of screen
    osdSetComponentPositionA(OSD_BITMAP2, 0x14 + (60*2), 0x12 + 100);
              //0x14 and 0x12 are equivalent to 0,0 position on LCD
              //we want it at 60,100 location:  x is doubled and added to 0x14 (x*2 is always
              //   used here for both video and bitmap layers).  y is just added to 0x12.

    //draw the words 'Please Wait!' on bitmap2, cause rest of drawing takes a while...
    //  This command graphicsString is explained in the next section of program.
    graphicsStringA(&screenBitmap2, 43, 8, &spriteFontCursive, cursive_, 9, 0, "Please Wait!");

    //enable bitmap1 component
    osdSetComponentConfigA(OSD_BITMAP2, OSD_COMPONENT_ENABLE
                                     | OSD_BITMAP_8BIT
                                     | OSD_BITMAP_MERGEBACK
                                     | OSD_BITMAP_A6);
         //show it on screen.  OSD_BITMAP_8BIT indicates 256-color (the max available)
         //OSD_BITMAP_MERGEBACK indicates blending mode.  The only other alternative available
         //   is OSD_BITMAP_0TRANS, see bitmap2 activation in Main Demo Loop below...
         //OSD_BITMAP_A6 sets blending, to make video layer show thru bitmap just a little.
         //   OSD_BITMAP_A0 will cause bitmap to disappear cause lower layers will cover it.
         //   OSD_BITMAP_A7 will make bitmap 100% visible, layers under will be invisible.
         //   Inbetween values cause varying amounts of opacity

    //draw a blue border 2pix wide around edge of the 320x240 screenVideo layer (VIDEO1)
    graphicsBoxfA(&screenVideo, 0, 0, 2, 240, 0x504050FF);
        //start at 0,0 and draw 2 wide 240 high in blue (Y2CbY1Cr order 32-bit) (left border)
    graphicsBoxfA(&screenVideo, 318, 0, 2, 240, 0x504050FF); //(right border)
    graphicsBoxfA(&screenVideo, 0, 0, 320, 2, 0x504050FF); // (top border)
    graphicsBoxfA(&screenVideo, 0, 238, 320, 2, 0x504050FF); // (bottom border)
    //now fill center of screenVideo with various colors
    for (x=2; x<318; x++) {
        for (y=2; y<238; y++) {
            c = 0xC0C04000 + ((x+y)<<8);   //just generate some various colors
            //draw one pixel at a time in x,y location with color c
            graphicsSetPixelA(&screenVideo, x, y, c);
        }
    }

    //draw a red border 2pix wide around edge of the 640x480 screenVideo2 layer (VIDEO2)
    graphicsBoxfA(&screenVideo2, 0, 0, 2, 480, 0x50FF5050);
    graphicsBoxfA(&screenVideo2, 638, 0, 2, 480, 0x50FF5050);
    graphicsBoxfA(&screenVideo2, 0, 0, 640, 2, 0x50FF5050);
    graphicsBoxfA(&screenVideo2, 0, 478, 640, 2, 0x50FF5050);
    //fill center of screenVideo2 with various colors/pattern
    for (x=2; x<638; x++) {
        for (y=2; y<478; y++) {
            c = 0xf0f0f0f0 - ((x*y) << 9);  //another random formula, turns out it looks cool
            //draw one pixel at a time in x,y location with color c
            graphicsSetPixelA(&screenVideo2, x, y, c);
        }
    }

//********New Stuff here:*********
    //draw a white border 2pix wide around edge of the 784x360 screenBitmap layer (BITMAP1)
    //Because of special tricks needed to do a smooth-scroll of large Bitmap layer, our final
    //   viewable size will be 6 pixels less wide:  778x360 -- see the DoScroll routine for
    //   explanations.  But the lost 6 pixels are at the left edge -- so the border below is
    //   is drawn 6 pixels in from the left edge, rather than at x position 0.
    graphicsBoxfA(&screenBitmap, 6, 0, 2, 360, 0xFFFF);
    graphicsBoxfA(&screenBitmap, 782, 0, 2, 360, 0xFFFF);
    graphicsBoxfA(&screenBitmap, 6, 0, 778, 2, 0xFFFF);
    graphicsBoxfA(&screenBitmap, 6, 358, 778, 2, 0xFFFF);
    //fill viewable area of Bitmap1 with various colors/pattern
    for (x=8; x<782; x++) {
        for (y=2; y<358; y++) {
            c = (x >> 3);
            graphicsSetPixelA(&screenBitmap, x, y, c);
        }
    }
    //Punch a couple holes in the bitmap one, with color 0 boxes, to test transparency later...
    graphicsBoxfA(&screenBitmap, 200,290,80,40, 0x0000);
    graphicsBoxfA(&screenBitmap, 400,80,100,100, 0x0000);

//*********End New Stuff**********

    //enable video1 component, we'll show that first
    osdSetComponentConfigA(OSD_VIDEO1, OSD_COMPONENT_ENABLE);


//------------------------ PRINT INITIAL TEXT IN VARIOUS PLACES ---------------------
    
    //clear the area that used to say "Please Wait!":
    graphicsBoxfA(&screenBitmap2, 10, 8, 180, 15, 0x1212); //draws box in gray
    
    //change to text color red for next textline:
    //(adjusts pal16 because we're printing on 16-bit graphics)
    //(adjusts color index 1 because that's the text color; index 0 is the background color)
    pal16[1] = 0xF9F9;  //0xf9 is red in the built-in 256-color pallette

    //Next statement prints string to screen.  The arguments are in this order:
    //1. Pointer to structure of video component to print to
    //2. x-location of upper left start
    //3. y-location of upper left start
    //4. Pointer to structure of font sprite to use
    //5. Pointer to actual font data (from the various fonts available in fonts.h)
    //6. horizontal amount of pixels to advance with each character...see below
    //7. vertical amount of pixels to advance with each character...see below
    //8. The text string (pointer to char array)
    //Arguments 6 and 7 allow you to print in different directions or spacings.
    //Typically you'd set horizontal advance to pixel width of one char (spriteFont5x8.width)
    //  so that each char takes minimum amount of space.  However, using a larger number
    //  provides a perfect way of spacing characters out to fill a larger area.
    //Typically you'd set vertical advance to 0, for horizontal text (no vertical advance).
    //  But, using higher than zero makes diagonal text, each character lower on screen.
    //Using hor. advance of zero with vert. advance equal or higher than real character height
    //  makes text print vertically!
    graphicsStringA(&screenBitmap2, 43, 8, &spriteFontCursive, cursive_, 9, 0, "Graphics Test");

    //change to yellow for next line
    pal16[1] = 0xFBFB;
    graphicsStringA(&screenBitmap2, 10, 26, &spriteFont5x8, std5x8_, 5, 0,
                  "This is Bitmap2 Component, 256 Color");
    //change back to white
    pal16[1] = 0xFFFF;
    //next line will print not transparent (that's how we defaulted spriteFont7x13)
    //with red as background color since we're using pal16 (printing to 16-bit graphics)
    //and the zero-index (text background) color was defined as red in initizalization
    //also its characters will be more spaced out, I used 10 for horizontal advance and the
    //actual character width is only 7.  Notice how it looks on screen.  If it were
    //also transparent, the spacing out wouldn't be so noticeable and would just look nice.
    graphicsStringA(&screenBitmap2, 12, 40, &spriteFont7x13, std7x13_, 10, 0,
                  "Controls/Settings:");

    graphicsStringA(&screenBitmap2, 15, 58, &spriteFont5x8, std5x8_, 5, 0,
                  "F1 - DISPLAY  [now: Video1]");
    graphicsStringA(&screenBitmap2, 15, 68, &spriteFont5x8, std5x8_, 5, 0,
                  "F2 - SCROLL   [now: Bitmap2]");
    graphicsStringA(&screenBitmap2, 15, 77, &spriteFont5x8, std5x8_, 5, 0,
                  "   (use joystick to scroll)");
    graphicsStringA(&screenBitmap2, 15, 86, &spriteFont5x8, std5x8_, 5, 0,
                  "F3 - SPEED    [now:  Medium]");

    //Few lines earlier we used the spriteFont7x13 on bitmap -- it produced white text with
    //no transpareny and red background.  We use it here again, with no changes, but it'll
    //produce white text with black background.  It's because we're now using it on the
    //video components, which means it looks at pal32 structure instead of pal16 to decide
    //what colors to use...
    graphicsStringA(&screenVideo, 10, 20, &spriteFont7x13, std7x13_, 7, 0,
                  "This is the Video1 Component.  It's 320x240");
    graphicsStringA(&screenVideo2, 10, 20, &spriteFont7x13, std7x13_, 7, 0,
                  "This is the Video2 Component.  It's sized 640x480 and scrollable in any direction.");

    //change to transparent mode for next lines and change color to red
    spriteFont7x13.transparent = 0;
    //alter pal32 this time cause we're printing on 32-bit video now.
    pal32[1] = 0x40FF4050;  //red in Y2CrY1Cb order
    graphicsStringA(&screenVideo, 40, 50, &spriteFont7x13, std7x13_, 7, 0,
                  "This Component can not be scrolled");
    //change to red
    pal32[1] = 0xFF90FF00;
    graphicsStringA(&screenVideo2, 10, 50, &spriteFont7x13, std7x13_, 7, 0,
                  "Component can be scrolled normal or smooth");

    //change color to purple for this line:
    pal32[1] = 0x50905090;
    //and set transparancy back to off but instead of black background use yellow:
    spriteFont7x13.transparent = -1;
    pal32[0] = 0xFF90FF00;  //color index 0 sets text background color
    graphicsStringA(&screenVideo2, 10, 250, &spriteFont7x13, std7x13_, 7, 0,
                  "Difference in normal & smooth horizontal scroll is obvious at medium or slow speeds...");

//********New Stuff here:*********
    graphicsStringA(&screenBitmap, 12, 20, &spriteFont7x13, std7x13_, 7, 0,
                  "This is the Bitmap1 Component.  It's sized 778x360 (viewable) and scrollable in any direction.");
    graphicsStringA(&screenBitmap, 12, 50, &spriteFont7x13, std7x13_, 7, 0,
                  "This component can be scrolled smoothly in this demo -- coarse scrolling is of course easier!");
    graphicsStringA(&screenBitmap, 12, 270, &spriteFont7x13, std7x13_, 7, 0,
                  "Made textbox (Bitmap2) NOT blended now cause it only blends properly w/video layers, not the other bitmap.");
    graphicsStringA(&screenBitmap, 12, 250, &spriteFont7x13, std7x13_, 7, 0,
                  "Bitmap1 demonstrates transparency also, you see parts of Video2 below the 'holes', where bitmap1 color is 0.");
//*********End New Stuff**********

    //set 5x8 font to what I need for rest of program
    pal16[0] = 0x1212;  //gray background
    spriteFont5x8.transparent = -1;  //not transparent so I can overwrite existing text
                                     //without having to "erase" is first...

//------------------------ MAIN LOOP FOR DEMO ---------------------------------------
    int key;
    int layer = 0; 
    while (1) {
        key = buttonsGetStatusA();
        if (key & BUTTONS_AV300_MENU1) {    //F1 button pressed, switch displayed video layer
            layer++; if (layer>2) layer = 0;
            if (layer==0) {  //enable video1, disable video2 and bitmap1
                osdSetComponentConfigA(OSD_VIDEO1, OSD_COMPONENT_ENABLE);
                osdSetComponentConfigA(OSD_VIDEO2, 0);
                osdSetComponentConfigA(OSD_BITMAP1, 0);
                //make sure our trick for smooth-scroll bitmap1 is reset
                osdSetMainShiftA(0x79,0);
                //make bitmap2 (textbox) blend again
                osdSetComponentConfigA(OSD_BITMAP2, OSD_COMPONENT_ENABLE
                                     | OSD_BITMAP_8BIT
                                     | OSD_BITMAP_MERGEBACK
                                     | OSD_BITMAP_A6);
                //update the text to reflect current mode!
                graphicsStringA(&screenBitmap2, 15, 58, &spriteFont5x8, std5x8_, 5, 0,
                  "F1 - DISPLAY  [now: Video1] ");

            }
            else if (layer==1) {  //enable video2, disable video1 and bitmap1
                osdSetComponentConfigA(OSD_VIDEO2, OSD_COMPONENT_ENABLE);
                osdSetComponentConfigA(OSD_VIDEO1, 0);
                osdSetComponentConfigA(OSD_BITMAP1, 0);
                //make sure our trick for smooth-scroll bitmap1 is reset
                osdSetMainShiftA(0x79,0);
                //make bitmap2 (textbox) blend again
                osdSetComponentConfigA(OSD_BITMAP2, OSD_COMPONENT_ENABLE
                                     | OSD_BITMAP_8BIT
                                     | OSD_BITMAP_MERGEBACK
                                     | OSD_BITMAP_A6);
                graphicsStringA(&screenBitmap2, 15, 58, &spriteFont5x8, std5x8_, 5, 0,
                  "F1 - DISPLAY  [now: Video2] ");
            }
//********New Stuff here:*********
            else { //enable bitmap1, disable video1 and enable video2 (for transparency test)
                osdSetComponentConfigA(OSD_VIDEO1, 0);
                osdSetComponentConfigA(OSD_VIDEO2, OSD_COMPONENT_ENABLE);
                //our trick #3 for smooth-scroll bitmap1:
                osdSetMainShiftA(0x6D,0);
                //activate bitmap1
                osdSetComponentConfigA(OSD_BITMAP1, OSD_COMPONENT_ENABLE
                                                     | OSD_BITMAP_8BIT
                                                     | OSD_BITMAP_0TRANS
                                                     | OSD_BITMAP_A0);
         //show it on screen.  OSD_BITMAP_8BIT indicates 256-color (the max available)
         //OSD_BITMAP_0TRANS is the alternative to OSD_BITMAP_MERGEBACK we used for Bitmap2:
         //   It is tranparency mode (instead of blending).  This makes Bitmap1 completely
         //   visible on top of lower layers, but makes Bitmap1's color '0' the transparent
         //   color, so anything drawn with color 0 will not be visible and instead allow
         //   any layers underneath to show thru in those spots.  Very necessary to use for
         //   for lots of situations.
         //OSD_BITMAP_A0 sets blending, but since we're not in a blending mode its use is
         //   different.  A0 is the typical, expected behavior setting:
         //   it will cause tranparent color (color #0) to not be drawn, and
         //   allow anything under to show through 100%.  A7 would cause transparent color to
         //   be shown completely, making NO actual tranparency.  Inbetween
         //   values would allow just a bit of layers underneath to show thru tranparent color
         //   areas, in effect blending for just those spots on Bitmap1 that are in Color #0.
                graphicsStringA(&screenBitmap2, 15, 58, &spriteFont5x8, std5x8_, 5, 0,
                  "F1 - DISPLAY  [now: Bitmap1]");
                osdSetComponentConfigA(OSD_BITMAP2, OSD_COMPONENT_ENABLE
                                                     | OSD_BITMAP_8BIT
                                                     | OSD_BITMAP_0TRANS
                                                     | OSD_BITMAP_A7);
                //makes Bitmap2 (textbox) not transparent to avoid problem of Bitmap2 not
                //seeming to use blending/transparency with Bitmap1 -- it instead shows
                //the blending/transpaency result with the video layers, and ignored the
                //bitmap1 layer that is underneath it.  This is not a desired result in
                //this case...so I just disabled any blending or transparency for textbox
                //when the user switches to display of bitmap1 background.
            }
//*********End New Stuff**********
            delay(0x10000);  //delay to avoid multiple keypresses too fast
        }
        if (key & BUTTONS_AV300_MENU2) {  //F2 button pressed, toggle scroll control
            scroll++; if (scroll>3) scroll=0;
            if (scroll==0) { //joystick controls will move bitmap layer
                graphicsStringA(&screenBitmap2, 15, 68, &spriteFont5x8, std5x8_, 5, 0,
                  "F2 - SCROLL   [now: Bitmap2]       ");
            }
            else if (scroll==1) { //joystick controls will move video2 (w/coarse horizontal)
                //reset stuff that was changed for smooth horiz scrolling video
                osdSetComponentSizeA(OSD_VIDEO2, 640, 240);
                osdSetComponentPositionA(OSD_VIDEO2, 0x14, 0x12);
                graphicsStringA(&screenBitmap2, 15, 68, &spriteFont5x8, std5x8_, 5, 0,
                  "F2 - SCROLL   [now: Video2 Normal] ");
            }
            else if (scroll==2) {  //joystick will move video2 (w/smooth horizontal scrolling)
                //do trick to allow smooth horizontal video scrolling (see "doScroll" routine)
                osdSetComponentSizeA(OSD_VIDEO2, 656, 240);
                graphicsStringA(&screenBitmap2, 15, 68, &spriteFont5x8, std5x8_, 5, 0,
                  "F2 - SCROLL   [now: Video2 Smooth] ");
            }
//********New Stuff here:*********
            else {  //joystick will move bitmap1 (w/smooth horizontal scrolling)
                //3 tricks used for smooth horizontal bitmap scrolling (see "doScroll" routine)
                graphicsStringA(&screenBitmap2, 15, 68, &spriteFont5x8, std5x8_, 5, 0,
                  "F2 - SCROLL   [now: Bitmap1 Smooth]");
            }
//*********End New Stuff**********
           delay(0x10000);
        }
        if (key & BUTTONS_AV300_MENU3) {  //F3 button pressed, switch between slow/fast scroll
            slow++; if (slow>2) slow=0;
            if (slow==0) {
                wait = 0x6000;
                graphicsStringA(&screenBitmap2, 15, 86, &spriteFont5x8, std5x8_, 5, 0,
                  "F3 - SPEED    [now:  Slow]  ");
            }
            else if (slow==1) {
                wait = 0x1200;
                graphicsStringA(&screenBitmap2, 15, 86, &spriteFont5x8, std5x8_, 5, 0,
                  "F3 - SPEED    [now:  Medium]");
            }
            else {
                wait = 0x0300;
                graphicsStringA(&screenBitmap2, 15, 86, &spriteFont5x8, std5x8_, 5, 0,
                  "F3 - SPEED    [now:  Fast]  ");
            }
            delay(0x10000);
        }
        if (key & BUTTONS_AV300_UP) doScroll(0,-1);
        if (key & BUTTONS_AV300_RIGHT) doScroll(1,0);
        if (key & BUTTONS_AV300_DOWN) doScroll(0,1);
        if (key & BUTTONS_AV300_LEFT) doScroll(-1,0);
        if (key & BUTTONS_AV300_OFF) return 0;
    }
}


//------------------------ ROUTINE TO SCROLL ----------------------------------------

void doScroll(int xdir, int ydir) {

    int pixshift;
    //First, handle scrolling of bitmap2 component...
    //This is easy, since bitmap2 window is smaller than screen, we just use the
    //   osdSetComponentPosition to place it in new spot.
    //This implements fine pixel-by-pixel scrolling easily.
    if (scroll==0) {
        xb += xdir; yb += ydir;  //move in proper direction
        //keep coordinates within range so whole bitmap2 component always stays on screen,
        //   since we want to keep the text inside readable and on-screen.
        if (xb<0) xb=0; if (yb<0) yb = 0;
        if (xb>120) xb=120; if (yb>140) yb = 140;
        //Set the new position -- as before, we double x direction, and we
        //  add the default top left position of 0x14,0x12 to both x and y:
        osdSetComponentPositionA(OSD_BITMAP2, 0x14 + (xb*2), 0x12 + yb);
        //use delay to avoid multiple keypresses being registered and scrolling too fast:
        delay(wait);
    }

    //OK, now we handle scrolling of the video2 component...
    //Since video2 is larger than screen, we can't use osdSetComponentPosition.
    //We have to use the osdSetComponentOffset control, so that we "move" through video memory
    //  and mimic scrolling that way.
    //Since offset is limited to nearest 32-byte boundary, we can only scroll in increments
    //  of eight pixels ONLY in a horizontal direction.  Vertical is fine, pixel-by-pixel
    else if (scroll==1) {
        xv += xdir; yv += ydir;
        //keep from scrolling too much out of boundary...always want to keep lcd full
        if (xv<0) xv = 0; if (yv<0) yv = 0;
        if (xv>320) xv = 320; if (yv>240) yv = 240;
        //here we set the offset:  base address for video2, PLUS
        //    y_position * bytes_per_pixel * width_in_pixels, PLUS x_position * bytes_per_pix
        //In this case it's video component, so 32-bit, means 4 bytes per pixel
        //    and width of video memory is 640 pixels across:
        //Note that this formula still sets offset at numbers other than 32-byte boundaries --
        //    That's OK, av300 just ignores it -- but the result is that the scroll will only
        //    show when this routine gets run 8 times (scrolling by 8pixels, which then has 
        //    advanced the offset to the next 32-byte boundary.
        //    I left it this way even though it seems useless to have to let it run 8 times
        //    before it actually scrolls -- the reason is that if I made it actually jump
        //    8 pixels (32bytes) every time this loop was run, then in use the horizontal
        //    scrolling would appear to move 8 times faster than vertical, and it'd be a mess
        //    to adjust the delay to fix it...
        osdSetComponentOffsetA(OSD_VIDEO2, 0x03e00000 + (yv * 4 * 640) + (xv * 4));
        //delay:
        delay(wait);
    }

    //Now, we handle the scrolling of video2 using a special trick to implement smooth
    //   horizontal scrolling, not limited by the 8-pixel limitation of above method.
    else if (scroll==2) {
        xv += xdir; yv += ydir;
        if (xv<0) xv = 0; if (yv<0) yv = 0;
        if (xv>320) xv = 320; if (yv>240) yv = 240;
        //First we use offset just like above.  It'll display to nearest 32-byte boundary,
        //   meaning nearest 8pixels horizontally
		osdSetComponentOffsetA(OSD_VIDEO2, 0x03e00000 + (yv * 4 * 640) + (xv * 4));
        //Now calculate how many pixels past nearest 8pix boundary for this desired position
		pixshift = xv % 8;
        //Now we use osdSetComponentPosition, which allows pixel-level positioning, in order
        //to shift entire display slightly (we need up to 7pix) in order to provide the smooth
        //scrolling we're looking for.  As in other uses of osdSetComponentPosition,
        //we must use double the x position (pixshift*2) and in this case we subtract it from
        //the default 0x14 (which was equal to 0 position at left edge of LCD).  We use the
        //default 0x12 for vertical since it doesn't need alteration.
		osdSetComponentPositionA(OSD_VIDEO2, 0x14 - (pixshift * 2), 0x12);
        //One important thing:  doing this position shifting, where we're moving display to
        //left by a few pixels, will cause the right edge of the display to show black or
        //garbage, because the OSD for video2 layer is only 320pixels wide, and we're shifting
        //the left-most pixels off the screen, leaving the right edge blank.
        //The fix was done back in main() main loop, we did the following for smooth scroll:
        //osdSetComponentSize(OSD_VIDEO2, 656, 240);
        //This tricks the OSD into making Video2 display 328 pixels on LCD
        //  (328*2=656, ComponentSize is always desired pixels * 2 for x direction).
        //  The extra 8 pixels means the video is drawn wider than the LCD can display
        //  which is exactly what we need for smooth scrolling.  Then we can shift as much as
        //  7 pixels to the left and not expose garbage on the right edge of display...!
        delay(wait);
    }

//********New Stuff here:*********
    //And finally, we handle the smooth scrolling of bitmap1 component, using more tricks.
    else {
        xb2 += xdir; yb2 += ydir;
        if (xb2<6) xb2 = 6; if (yb2<0) yb2 = 0;
        if (xb2>464) xb2 = 464; if (yb2>120) yb2 = 120;
        //We do it *basically* like above smooth video example, but there's some serious
        //  problems:  First, since bitmap is 16-bits/pixel, and OSD Offset is limited still
        //  to 32-byte boundaries, that means that the OSD Offset control will now only get
        //  within the nearest *16 pixels* instead of the nearest 8pix we had for video layer.
        //That would be no big deal, except for one thing:  We then used OSD ComponentPosition
        //  to get the other 8 pixels of accuracy for smooth scrolling.  If we do the same
        //  here for bitmap, there's a problem:  ComponentPosition is always shifted by
        //  subtracting for horizontal:  0x14 - (2 * number_of_desired_pixels_to_shift).
        //  Now that we may need as many as 16 pixels fine shifting, that would yield some
        //  negative numbers, in fact anytime we needed more than 10 pixels fine shift.
        //There's nothing we can do about the 0x14 number, that's what is needed to make the
        //  layer display at left edge of screen.  If we use a larger number, the whole screen
        //  gets moved to the right, and so our appearance of a smooth scroll would get ruined.
        //Luckily, there's another solution!  We can first indeed use a larger number for
        //  ComponentPosition, we'll need 0x20 as a basis to allow up to 16 pixels fine shift:
        //  (0x20 = dec 32, and so shifting 16 pix to left would be 0x20 - 16*2, just enough.
        //  Now display is bad since the whole display will be 6 pixels too far to the right
        //  due to using 0x20 as a basis rather than 0x14.  We can fix that by using another
        //  function:  osdSetMainShift.  Takes 2 arguments, x and y, and sets an OVERALL
        //  shifting for the on-screen display.
        //The bad news is that this control affects *ALL* OSD layers, everything,
        //  and will shift it all around...  But it's the only
        //  way I've found to implement perfect smooth scrolling of a large bitmap layer!
        //  So, you've been warned:  using this when other layers are present will cause them
        //  all to get shifted around -- this means if you need smooth large bitmap scrolling
        //  you'll have to design your other layers with this in mind, and use 0x20 for the
        //  horizontal default positioning of ALL layers with their osdSetComponentPosition!
        //  You'll have to make them all also six pixels wider using osdSetComponentSize,
        //  and then not bother drawing to the leftmost 6 columns cause they're useless.
        //  Position (6,0) on all layers would then be the upperleft corner for instance.
        //So, ComponentPosition of 0x20 horizontal is used as the default positioning for
        //  the large bitmap2 layer.  Then osdSetMainShift will be used to change overall
        //  display 6 pixels to the left of normal default setting!  Then we can do our normal
        //  smooth crolling methods, and everything will look perfect.
        //Oh, except for one thing:  we're sacrificing the left-most 6 columns of pixels for
        //  this, so those are unusable.  This also means that the display needs to be 6pix
        //  wider, in order to ensure that the right edge is extended far enough still.
        //  In video example, osdSetComponentSize was enlarged by 8 pixels, enough in that
        //  video layer example in order to ensure screen always was full.  For bitmap here,
        //  since we have to fine-scroll up to 16pix inside each coarse scroll segment,
        //  we'll first have to make this layer diplay 16 pixels wider than the LCD.
        //  THEN, since we're losing 6 more pixels, due to the overall osdSetMainShift trick,
        //  we'll have to set osdSetConponentSize to a total of 22 pixels larger than normal.

        //OK, so now I can finally explain the three 'tricks', the commands in various places
        //  that set up the capability for the fine large bitmap scrolling:
        //  (the first 2 were done in the initialization of BITMAP1, the third trick
        //   is done in the Main Loop of the demo whenever user switches to display bitmap1)
        //  1) osdSetComponentSizeA(OSD_BITMAP1, 684, 240):  sets display screen width to
        //        be 22 pixels wider than normal:  always number of pixels * 2, so:
        //        (320 + 22) * 2 = 684!  (320 is the normal size of LCD display screen width)
        //  2) osdSetComponentPositionA(OSD_BITMAP1, 0x20, 0x12):  sets basic 'home' position
        //        of display 6 pixels farther to right than normal (0x14 is normal), and
        //        0x14 = 20decimal, so 20 + 6*2 = 32 = 0x20 hex.  Always use pixels*2 here.
        //        In the initialization section, I actually used 0x20 - 12, it's because I
        //        wanted to set the initial view properly at the upper left of our window,
        //        which is 6pixels in, hence 0x20 - 6*2.  Now that seems silly, it's the
        //        same as the non-trick version of 0x14, but I'm showing it here for clarity,
        //        since for the actual fine scrolling we do always use 0x20 - pixshift*2
        //  3) osdSetMainShiftA(0x6D,0):  This is the trick that shifts everything 6 pixels
        //        to the left, to compensate for #2 trick and keep display looking perfect.
        //        Turns out the default for this (normal position of all layers on LCD) is
        //        0x79 for x and 0 for y.  Larger x numbers shift right, larger y numbers
        //        shift down.  We need to go 6 pixels to left.  This control also needs
        //        the number of pixels * 2, so:  0x79 (default) = 121 decimal.
        //        121 - 6*2 = 109 = 0x6D hex.
        //  Note that in this example I reset osdSetMainShift back to default of (0x79,0)
        //    whenever the user changes the view back to a different scroll layer -- I didnt
        //    feel like rewriting all the otherlayers to accomodate a shift of 6 pixels.
        //    Not necessary since I don't need all layers showing up at the same time, and
        //    heck it's just a demo :)  But you can see the effect of the osdSetMainShift
        //    change when you switch display to bitmap1:  the bitmap2 layer is also visible
        //    at the time and you see it suddenly jump 6 pixels to the left...

        //Without further ado, here's the smooth scrolling code for large bitmaps now:

		osdSetComponentOffsetA(OSD_BITMAP1, 0x03a00000 + (yb2 * 2 * 784) + ((xb2) * 2));
		pixshift = xb2 % 16;
		osdSetComponentPositionA(OSD_BITMAP1, 0x20 - (pixshift * 2), 0x12);

        //Three lines of code, 2 screenfuls of explanation!!  Damn...
        //The only differences:  osdSetComponentOffset multiplies everything *2 instead of *4
        //   since bitmaps layers are just 2bytes/pixel, not 4.  Also we used 784 to
        //   calculate offset because that's the actual full width in memory of this layer,
        //   and also notice way above that xb2 (current x-position of scroll) is kept above
        //   6 at minimum, because again the left-most 6pixels are not being used...
        //Next, pixshift calculates remainder to nearest 16 pixels instead of 8.
        //Last, osdSetComponentPositionA subtracts for 0x20 rather to 0x14 to calculate horiz.
        delay(wait);
    }
//*********End New Stuff**********
}


//----routine to provide delay-----
void delay(unsigned int time) {
    for (;time>0;time--) ;
}
