<?
	$style="<style type='text/css'>\n";
	$style.="a:link,a:active,a:visited { text-decoration: none; color:black; }\n";
	$style.="a:hover { text-decoration: underline; color:blue; }\n";
	$style.=".forumline	{ background-color: #FFFFFF; border: 1px #8F8D8E solid; }\n";
	$style.=".forumline2	{  border: 0px ; }\n";
	$style.="</style>";

	$CoTable="#EEEEEE";
	$CoTR="#E4EBF2";
	
	//$CoHead="#EBBABB";
	$CoHead="#E87A7C";
	//$CoCel="#E4EBF2";
	$CoCel="#E3E3E3";
	//$CoMsg="#A0D7B0";
	$CoMsg="#CCCCCC";
	//$CoNonLu="#FFB648";
	$CoNonLu="#A1D394";

	$largeurTab = 700;

	$titre="<strong>LinAV</strong> - porting uClinux to archos multimedia device (Av320/Av340/Av380)\n";
?>
