GCCFLAGS = -Wall  -mlong-calls -fomit-frame-pointer -nostdlib -fno-builtin  -mcpu=arm7tdmi 
#-Os 

GCCFLAGS +=    -fno-strict-aliasing


ASFLAGS = -mfpu=softfpa

# target AV3XX or GMINI4XX

TARGET_DEVICE = GMINI4XX

GCCFLAGS += -D$(TARGET_DEVICE)
ASFLAGS  += --defsym $(TARGET_DEVICE)=1


# GFX_MODE : DPLANE or GFX_CTX
GFX_MODE = DPLANE
#other config
# HAVE_BAT_POWER has to be set atm, it used to turn off lcd, HD and device
HAVE_BAT_POWER = 1
# if HAVE_USB_FW is not set, HD timer might mess with USB when USB is plugged and enable
HAVE_USB_FW = 0
HAVE_EXT_MODULE = 0
HAVE_FM_REMOTE = 0
HAVE_SOUND = 0
HAVE_CMD_LINE = 1
HAVE_EVT = 1

ifeq ($(HAVE_BAT_POWER),1)
	GCCFLAGS += -DHAVE_BAT_POWER
endif

ifeq ($(HAVE_EXT_MODULE),1)
	GCCFLAGS += -DHAVE_EXT_MODULE
endif

ifeq ($(HAVE_FM_REMOTE),1)
	GCCFLAGS += -DHAVE_FM_REMOTE
endif

ifeq ($(HAVE_SOUND),1)
	GCCFLAGS += -DHAVE_SOUND
endif

ifeq ($(HAVE_USB_FW),1)
	GCCFLAGS += -DHAVE_USB_FW
endif

ifeq ($(HAVE_CMD_LINE),1)
	GCCFLAGS += -DHAVE_CMD_LINE
endif

ifeq ($(HAVE_EVT),1)
	GCCFLAGS += -DHAVE_EVT
endif

GCCFLAGS += -D${GFX_MODE}


# Font definition:
FONT_LIST = 4x6 6x9 8x13

TOOL=arm-linux-uclibc
GCC=$(TOOL)-gcc
AS=$(TOOL)-as
LD=$(TOOL)-ld
OBJCOPY= $(TOOL)-objcopy
RM=rm
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib
