GCCFLAGS = -Wall -mlong-calls -nostdlib -fno-builtin -fomit-frame-pointer -mcpu=arm7tdmi -Os 

GCCFLAGS += -fno-strict-aliasing

ASFLAGS = -mfpu=softfpa

#GFX_MODE : DPLANE or GFX_CTX
GFX_MODE = DPLANE




GCCFLAGS += -D${GFX_MODE}

TOOL=arm-linux-uclibc
GCC=$(TOOL)-gcc
AS=$(TOOL)-as
LD=$(TOOL)-ld
OBJCOPY= $(TOOL)-objcopy
RM=rm
AR=$(TOOL)-ar
RANLIB=$(TOOL)-ranlib
