# ARM toolchain root directory
#BUILDDIR = /home/jimmy/archos/uclib/toolchain/gcc-3.3.x/toolchain_arm_nofpu
BUILDDIR = /home/jimmy/armdevroot/
BUILDVER = 3.4.2

GCCINCDIR = $(GCCINCDIRS) -I$(BUILDDIR)/lib/gcc/arm-linux-uclibc/$(BUILDVER)/include/
#GCCINCDIR = $(GCCINCDIRS) -I$(BUILDDIR)/arm-linux/include/ -I$(BUILDDIR)/lib/gcc-lib/arm-linux-uclibc/3.3.3/include
# Toolchain default make flags
GCCFLAG = -Wa,-R -fno-zero-initialized-in-bss -Wall $(GCCFLAGS) $(GCCINCDIR)
LDFLAG  = -L$(BUILDDIR)/lib/gcc/arm-linux-uclibc/$(BUILDVER)/ $(LDFLAGS)
ASFLAG  = -mfpu=softfpa $(ASFLAGS)

# ARM toolchain macros
ADDR2LINE = arm-linux-addr2line
AR        = arm-linux-ar
AS        = arm-linux-as
C++       = arm-linux-c++
C++FILT   = arm-linux-c++filt
CPP       = arm-linux-cpp
G++       = arm-linux-g++
GCC       = arm-linux-gcc
GCCBUG    = arm-linux-gccbug
GCOV      = arm-linux-gcov
LD        = arm-linux-ld
NM        = arm-linux-nm
OBJCOPY   = arm-linux-objcopy
OBJDUMP   = arm-linux-objdump
RANLIB    = arm-linux-ranlib
READELF   = arm-linux-readelf
SIZE      = arm-linux-size
STRINGS   = arm-linux-strings
STRIP     = arm-linux-strip

.SUFFIXES: .c .S .O .o

# Special make rule to use cross asmbler
.S.O:
	$(AS) $(ASFLAG) -o $@ $<

# Special make rule to use cross compiler
.c.o:
	$(GCC) $(GCCFLAG) -c -o $@ $<
