#define DUMMY1 (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++; (*DSP_TEST)++;

#define DUMMY DUMMY1

//#define DUMMY DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1; DUMMY1;

int dummy()
{
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
  DUMMY;
}

