#include <stdio.h>
#include <stdlib.h>

#include "../include/gui_pal.h"

double dist_3D(unsigned char r,unsigned char g,unsigned char b,
                unsigned char pr,unsigned char pg,unsigned char pb)
{
    double u,v,w,pu,pv,pw;
    double res;
    /*printf("pix=[0x%02x,0x%02x,0x%02x] pal=[0x%02x,0x%02x,0x%02x]",
                r,g,b,
                pr,pg,pb);*/
    
    u=(double)r;
    v=(double)g;
    w=(double)b;
    pu=(double)pr;
    pv=(double)pg;
    pw=(double)pb;
    
    res=sqrt(abs(u-pu)*abs(u-pu)+abs(v-pv)*abs(v-pv)+abs(w-pw)*abs(w-pw));
    //printf("%f\n",res);
    return res;
}

void doPrint(int index,float val,unsigned char r,unsigned char g,unsigned char b,
                unsigned char pr,unsigned char pg,unsigned char pb)
{
    printf("i=%d dist=%f pix=[0x%02x,0x%02x,0x%02x] pal=[0x%02x,0x%02x,0x%02x]\n",index,val,
                r,g,b,
                pr,pg,pb);
}

int get_nearest(unsigned char r,unsigned char g,unsigned char b)
{
    int min_index=0;
    double min_val=500;
    double new_val;
    int i;
    for(i=0;i<256;i++)
    {
        new_val=dist_3D(r,g,b,gui_pal[i][0],gui_pal[i][1],gui_pal[i][2]);
        if(new_val==0)
        {
            min_index=i;
            min_val=new_val;
            break;
        }
        if(new_val<min_val)
        {
            min_val=new_val;
            min_index=i;
        }
    }
    
    /*doPrint(min_index,min_val,r,g,b,
        (unsigned char)gui_pal[min_index][0],(unsigned char)gui_pal[min_index][1],(unsigned char)gui_pal[min_index][2]);*/
    
    return min_index;
}

/*void show_pal(void)
{
    unsigned char * pixel;
    int i;
    for(i=0;i<256;i++)
    {
        pixel=(unsigned char *)gui_pal[i];
        printf("r=%d,g=%d,b=%d\n",pixel[0],pixel[1],pixel[2]);
    }
}*/

int main(int argc, char* argv[]) {
    int w,h,i,j,c;
    int stop=0;    
    unsigned char rgb[3];
    int match_col;
    
    FILE* infile;
    FILE* outfile;
    
    if (argc != 6)
    {
        fprintf(stderr,"Info: %s source destination variable width height\n",argv[0]);
        exit(1);
    }

    infile = fopen(argv[1], "rb");

    if (!infile)
    {
        printf("Can't open file '%s' for reading!\n", argv[1]);
        exit(1);
    }
    
    outfile = fopen(argv[2], "w");
    
    w=atoi(argv[4]);
    h=atoi(argv[5]); 
    
    /*printf("Using palette: \n");
    show_pal();*/
    printf("Starting conversion: src=%s dest=%s vars:%s_da %s dim=(%d,%d)\n",argv[1],argv[2],argv[3],argv[3],w,h);
    
    fprintf(outfile,"/*\n* %s\n",argv[2]);
    fprintf(outfile,"*\n* linav - http://linav.sourceforge.net\n");
    fprintf(outfile,"* Copyright (c) 2004 by Christophe THOMAS\n");
    fprintf(outfile,"*\n* All files in this archive are subject to the GNU General Public License.\n");
    fprintf(outfile,"* See the file COPYING in the source tree root for full license agreement.\n");
    fprintf(outfile,"* This software is distributed on an \"AS IS\" basis, WITHOUT WARRANTY OF ANY\n");
    fprintf(outfile,"* KIND, either express of implied.\n");
    fprintf(outfile,"*\n*File generated by %s from %s, (w=%d,h=%d)\n",argv[0],argv[1],w,h);
    fprintf(outfile,"*/\n\n");
    fprintf(outfile,"#include \"graphics.h\"\n\n");
    fprintf(outfile,"unsigned char %s_da[%d][%d] = {\n",argv[3],h,w);
    
    for(i=0;i<h && !stop;i++)
    {
        if(i!=0)
            fprintf(outfile,",\n");
        fprintf(outfile,"{ ");
        for(j=0;j<w;j++)
        {
            if(j!=0)
                fprintf(outfile,", ");
            if (feof(infile)) {stop=1;break;}
            c = fread(rgb, 1, 3, infile);
            if (c == 0) {stop=1;break;}
            if (c != 3) {fprintf(stderr,"\nMismatch!\n\n");stop=1;break;}
            
            match_col=get_nearest(rgb[0],rgb[1],rgb[2]);
            if(!(j % 20)) fprintf(outfile,"\n    ");
            fprintf(outfile,"0x%02x",match_col);
        }
        fprintf(outfile,"\n}");
    }
    fprintf(outfile,"};\n\n");
    fprintf(outfile,"BITMAP %s = {(unsigned int) %s_da, %d, %d, 0, 0};\n\n",argv[3],argv[3],w,h);
    fclose(infile);
    
    return 0;
}
