
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char* argv[]) {
    int w,h,i,j,c,ept;
    int stop=0;
    int count;
    int binOut;
    unsigned char rgb[3];
    int r,g,b,y,cr,cb;
    
    FILE* infile;
    FILE * outfile;    

    if(argc == 5)
    {
        binOut=1;
        w=atoi(argv[3]);
        h=atoi(argv[4]); 
    }
    else
    {
        if (argc != 6)
        {
            fprintf(stderr,"Info: %s source destination variable width height\n",argv[0]);
            exit(1);
        }
        
        binOut=0;
        w=atoi(argv[4]);
        h=atoi(argv[5]); 
    }   

    infile = fopen(argv[1], "rb");

    if (!infile)
    {
        printf("Can't open file '%s' for reading!\n", argv[1]);
        exit(1);
    }
    
    if(binOut)
        outfile = fopen(argv[2], "wb");
    else
        outfile = fopen(argv[2], "w");

    if (!outfile)
    {
        printf("Can't open file '%s' for writing!\n", argv[2]);
        fclose(infile);
        exit(1);
    }
    
    if(!binOut)
    {
        fprintf(outfile,"/*\n* %s\n",argv[2]);
        fprintf(outfile,"*\n* linav - http://linav.sourceforge.net\n");
        fprintf(outfile,"* Copyright (c) 2004 by Christophe THOMAS\n");
        fprintf(outfile,"*\n* All files in this archive are subject to the GNU General Public License.\n");
        fprintf(outfile,"* See the file COPYING in the source tree root for full license agreement.\n");
        fprintf(outfile,"* This software is distributed on an \"AS IS\" basis, WITHOUT WARRANTY OF ANY\n");
        fprintf(outfile,"* KIND, either express of implied.\n");
        fprintf(outfile,"*\n*File generated by %s from %s, (w=%d,h=%d)\n",argv[0],argv[1],w,h);
        fprintf(outfile,"*/\n\n");
        //fprintf(outfile,"#ifndef %s \n#define %s \n\n",argv[2],argv[2]);
        fprintf(outfile,"unsigned int %s[%d][%d] = {\n", argv[3],h,w);
    }

    
    for(i=0;i<h && !stop;i++)
    {
        if(i>0 && !binOut)
            fprintf(outfile,",\n");
        if(!binOut)
            fprintf(outfile,"   {");
        count=0;
        for(j=0;j<w;j++)
        {
            if (feof(infile)) {stop=1;break;}
            c = fread(rgb, 1, 3, infile);
            if (c == 0) {stop=1;break;}
            if (c != 3) {fprintf(stderr,"\nMismatch!\n\n");stop=1;break;}
            r  = rgb[0];
            g  = rgb[1];
            b  = rgb[2];
            y  =  299*r +  587*g + 114*b;
            cb = -169*r + -331*g + 500*b + 128000;
            cr =  500*r -  419*g -  81*b + 128000;
            
            y = (y+500)/1000;
            cb = (cb+500)/1000;
            cr = (cr+500)/1000;
    
            if (y < 0) y = 0;
            if (y > 255) y = 255;
            if (cb < 0) cb = 0;
            if (cb > 255) cb = 255;
            if (cr < 0) cr = 0;
            if (cr > 255) cr = 255;
            
            if(j>0 && !binOut)
                fprintf(outfile,", ");
            if(!(count % 5) && !binOut) fprintf(outfile,"\n");
            if(binOut)
            {
                fputc(cb,outfile);
                fputc(y,outfile);
                fputc(cr,outfile);
                fputc(0x80,outfile);
            }            
            else
                fprintf(outfile,"0x80%02x%02x%02x", cr, y, cb);            
            count++;
        }
        if(!binOut)
            fprintf(outfile,"}");
        else
        {
            ept=32-w%32;
           // printf("%d:%d\n",i,ept);
           if(w%32)
           {
            for(ept=32-w%32;ept>0;ept--)
            {
                fputc(0x80,outfile);
                fputc(0xFF,outfile);
                fputc(0x80,outfile);
                fputc(0x80,outfile);
            }
            }
            
        }
    }
    if(!binOut)
        fprintf(outfile,"\n};\n\n");
    //fprintf(outfile,"#endif\n\n");
    
    fclose(infile);
    fclose(outfile);
    
    return 0;
}
